[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "11155111" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
